secretish_balloting/balloting/urls.py
from django.urls import path

from . import views

app_name = "balloting"
urlpatterns = [
    path("emailer/", views.email_unemailed, name="email_unemailed"),
    path(
        "<str:ballot_summary_fragment>/results/",
        views.ballot_results,
        name="ballot_results",
    ),
    path("<str:ballot_fragment>/<str:voter_fragment>/", views.vote, name="vote"),
    path(
        "<str:ballot_fragment>/<str:voter_fragment>/summary/",
        views.voting_summary,
        name="voting_summary",
    ),
]

secretish_balloting/secretish_balloting/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("balloting.urls")),
]

secretish_balloting/balloting/models.py
import datetime
import random

from django.db import models, transaction, IntegrityError
from django.utils import timezone
from django.utils.crypto import get_random_string


class Ballot(models.Model):
    name_text = models.CharField(max_length=100)
    opening_date = models.DateTimeField("opening date and time")
    closing_date = models.DateTimeField("closing date and time")
    url_fragment_text = models.CharField(
        max_length=40, help_text="Slug text to be used in the urls for this ballot"
    )
    url_summary_fragment_text = models.CharField(
        max_length=40,
        help_text="Slug text to be used in the summary url for this ballot",
    )

    def __str__(self):
        return self.name_text

    def is_open(self):
        return self.opening_date <= timezone.now() <= self.closing_date

    is_open.admin_order_field = "opening_date"
    is_open.boolean = True
    is_open.short_description = "Ballot open?"

    def save(self, *args, **kwds):
        if self.url_summary_fragment_text is None:
            self.url_summary_fragment_text = random.randint(10000000, 99999999)
        super().save(*args, **kwds)


class Question(models.Model):
    ballot = models.ForeignKey(Ballot, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=100)
    order_int = models.IntegerField("Question order")

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)

    def __str__(self):
        return self.choice_text


class Voter(models.Model):
    ballot = models.ForeignKey(Ballot, on_delete=models.CASCADE)
    email_text = models.EmailField("Email address")
    description_text = models.CharField(
        "Description", max_length=200, help_text="A descriptive note for this voter"
    )
    emailed_bool = models.BooleanField(
        "Voter has been emailed voting instructions", default=False
    )
    url_fragment_text = models.CharField(
        max_length=20, unique=True, null=True, blank=True, default=None
    )

    def __str__(self):
        return self.description_text

    def save(self, *args, **kwds):
        if self.url_fragment_text is None:
            # get current url fragments to ensure a unique one
            fragments = [o.url_fragment_text for o in Voter.objects.all()]
            while True:
                self.url_fragment_text = random.randint(10000000, 99999999)
                if self.url_fragment_text not in fragments:
                    break
        super().save(*args, **kwds)


class Vote(models.Model):
    voter = models.ForeignKey(Voter, on_delete=models.CASCADE)
    choice = models.ForeignKey(
        Choice, null=True, default=None, on_delete=models.CASCADE
    )

secretish_balloting/balloting/views.py
from collections import defaultdict, Counter
import os

from django.contrib.admin.views.decorators import staff_member_required
from django.core.mail import send_mass_mail
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from dotenv import load_dotenv

from .models import Ballot, Question, Choice, Voter, Vote

load_dotenv()


def vote(request, ballot_fragment, voter_fragment):
    ballot = get_object_or_404(Ballot, url_fragment_text=ballot_fragment)
    dt = timezone.now()
    if dt < ballot.opening_date:
        return HttpResponse(
            f"<h2>The {ballot.name_text} ballot has not opened yet. It will open at {ballot.opening_date:%H:%M SAST on %d %B %Y}</h2>"
        )
    if dt > ballot.closing_date:
        return HttpResponse(
            f"<h2>The {ballot.name_text} ballot closed at {ballot.closing_date:%H:%M SAST on %d %B %Y}.</h2>"
        )
    voter = get_object_or_404(Voter, url_fragment_text=voter_fragment)
    questions = Question.objects.filter(ballot=ballot).order_by("order_int").all()
    if request.method == "POST":
        choices = [
            int(request.POST.get(f"question{q.order_int}_choice"))
            for q in questions
            if request.POST.get(f"question{q.order_int}_choice")
        ]
        if len(choices) == len(questions):
            votes = Vote.objects.filter(voter=voter).all()
            if votes:
                votes.delete()
            for choice in choices:
                v = Vote(voter=voter, choice_id=choice)
                v.save()
            return HttpResponseRedirect(
                reverse(
                    "balloting:voting_summary",
                    args=(
                        ballot_fragment,
                        voter_fragment,
                    ),
                )
            )
        else:
            error_message = "Please select an option for each question"
    else:
        error_message = None
    return render(
        request,
        "balloting/vote.html",
        {
            "ballot": ballot,
            "voter": voter,
            "questions": questions,
            "error_message": error_message,
        },
    )


def voting_summary(request, ballot_fragment, voter_fragment):
    ballot = get_object_or_404(Ballot, url_fragment_text=ballot_fragment)
    dt = timezone.now()
    if dt < ballot.opening_date:
        return HttpResponse(
            f"<h2>The {ballot.name_text} ballot has not opened yet. It will open at {ballot.opening_date:%H:%M SAST on %d %B %Y}</h2>"
        )
    voter = get_object_or_404(Voter, url_fragment_text=voter_fragment)
    votes = (
        Vote.objects.filter(voter=voter).order_by("choice__question__order_int").all()
    )
    summary = [(v.choice.question.question_text, v.choice.choice_text) for v in votes]
    return render(
        request,
        "balloting/summary.html",
        {
            "ballot": ballot,
            "voter": voter,
            "summary": summary,
            "closed": dt > ballot.closing_date,
        },
    )


def ballot_results(request, ballot_summary_fragment):
    ballot = get_object_or_404(
        Ballot,
        url_summary_fragment_text=ballot_summary_fragment,
    )
    num_voters = len(Voter.objects.filter(ballot=ballot).all())
    votes = (
        Vote.objects.filter(choice__question__ballot=ballot)
        .order_by("choice__question__order_int")
        .all()
    )
    results_dict = defaultdict(Counter)
    questions = Question.objects.filter(ballot=ballot).all()
    for question in questions:
        for choice in Choice.objects.filter(question=question).all():
            results_dict[question][choice] = 0
    for v in votes:
        results_dict[v.choice.question][v.choice] += 1
    results_list = []
    for (question, choices) in results_dict.items():
        cl = [
            [frequency, choice.choice_text] for (choice, frequency) in choices.items()
        ]
        cl.sort(reverse=True)
        num_votes = sum([c[0] for c in cl if c[0]])
        for c in cl:
            if num_votes == 0:
                percentage = 0
            else:
                percentage = c[0] / (num_votes * 1.0) * 100.0
            c.append(f"{percentage:.2f}")
        if num_voters == 0:
            percentage = 0
        else:
            percentage = num_votes / (num_voters * 1.0) * 100.0
        results_list.append(
            (
                question.order_int,
                question.question_text,
                num_votes,
                num_voters,
                f"{percentage:.2f}",
                cl,
            )
        )
    results_list.sort()
    return render(
        request,
        "balloting/results.html",
        {
            "ballot": ballot,
            "now": timezone.now(),
            "results": results_list,
        },
    )


@staff_member_required
def email_unemailed(request):
    voters = Voter.objects.filter(emailed_bool=False)
    if request.method == "GET":
        return render(request, "balloting/emailer.html", {"voters": voters})
    with open("balloting/email_templates/instructions.txt") as fh:
        template = fh.read()
    emails = []
    for voter in voters:
        ballot = Ballot.objects.filter(voter=voter).first()
        url = reverse(
            "balloting:vote",
            args=(
                ballot.url_fragment_text,
                voter.url_fragment_text,
            ),
        )
        msg = template.format(
            **{
                "ballot_name": ballot.name_text,
                "start": ballot.opening_date.strftime("%H:%M on %d/%m/%Y"),
                "end": ballot.closing_date.strftime("%H:%M on %d/%m/%Y"),
                "contact_name": os.getenv("CONTACT_NAME"),
                "contact_email": os.getenv("CONTACT_EMAIL"),
                "url": f"{os.getenv('BASE_URL')}{url}",
            }
        )

        emails.append(
            (
                f"Voting details for the {ballot.name_text} ballot",
                msg,
                None,
                [voter.email_text],
            )
        )
    if emails:
        try:
            send_mass_mail(emails)
        except Exception as e:
            return HttpResponse(f"Error sending emails: {e}")
        for voter in voters:
            voter.emailed_bool = True
            voter.save()
        return HttpResponse(
            f"<h2>{len(emails)} email{'s' if len(emails) > 1 else ''} sent.</h2>"
        )
    return HttpResponse(
        f"<h2>All voters have been emailed before - no emails were sent.</h2>"
    )

secretish_balloting/balloting/templates/balloting/emailer.html
<h1>Emailer Tool</h1>

This page provides a tool to send voting instructions to any voter who has not yet been emailed.

{% if voters %}
These voters will be emailed:

<ul>
{% for voter in voters %}
    <li>{{ voter.email_text }} - {{voter.description_text }}</li>
{% endfor %}
</ul>

<form action="{% url 'balloting:email_unemailed' %}" method="post">
{% csrf_token %}
<input type="submit" value="Send Emails">
</form>
{% else %}
<p>
There are no voters who have not been emailed.
{% endif %}

secretish_balloting/balloting/templates/balloting/results.html
<h1>{{ballot.name_text}} ballot summary as at {{ now }}</h1>

{% for q in results %}
    <h3>Question: {{ q.1 }}</h3>
    <ul>
      {% for c in q.5 %}
          <li> {{ c.1 }}: {{ c.0 }} votes ({{ c.2 }}%)</li>
      {% endfor %}
          <li> <strong> Total votes cast: {{ q.2 }} ({{q.4}}%)</strong></li>
          <li> <strong> Total number of available votes: {{ q.3 }} </strong></li>
    </ul>
{% endfor %}

secretish_balloting/balloting/templates/balloting/summary.html
<h1>Vote summary</h1>

Thank you for voting in the {{ballot.name_text}} ballot. A summary of your votes is below:

{% for s in summary %}
    <h3>Question: {{ s.0 }}</h3>
    <ul><li>You selected "{{ s.1 }}"</li></ul>
{% endfor %}

{% if closed %}
    This ballot has closed - no further votes can be cast. Thank you for casting your vote.
{% else %}
    If you wish to change your vote, please <a href="{% url 'balloting:vote' ballot.url_fragment_text voter.url_fragment_text %}">click here</a> to vote again. <strong>Note that only your most recent vote will be recorded.</strong>
    <p>If you are satisfied with your vote you can close this webpage. Thank you for casting your vote.
{% endif %}

secretish_balloting/balloting/templates/balloting/vote.html
<h1>{{ ballot.name_text }}</h1>

{% if error_message %}<p><strong class="error_message">{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'balloting:vote' ballot.url_fragment_text voter.url_fragment_text %}" method="post">
{% csrf_token %}
{% for question in questions.all %}
    <h2>{{ question.question_text }}</h2>
    {% for choice in question.choice_set.all %}
        <input type="radio" name="question{{ question.order_int}}_choice" id="question{{ question.order_int}}_choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="question{{ question.order_int}}_choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
{% endfor %}
<p>
<input type="submit" value="Record vote">
</form>